// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento_box: dynamic(() => import("./BentoBox")),
  color_changer: dynamic(() => import("./ColorChanger")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  purchase_cta_button: dynamic(() => import("./PurchaseCtaButton")),
  switch_playground: dynamic(() => import("./SwitchPlayground")),
};
